[workspace]
members = [
    "pkgar",
    "pkgar-core",
    "pkgar-keys",
    "pkgar-repo",
]

[patch.crates-io]
ring = { git = "https://gitlab.redox-os.org/redox-os/ring.git", branch = "redox-0.16.20" }
tokio = { git = "https://gitlab.redox-os.org/redox-os/tokio.git", branch = "redox-1.17.0" }
