[package]
name = "pkgar-repo"
version.workspace = true
description = "Redox Package Repository"
license = "MIT"
authors = ["Jeremy Soller <jackpot51@gmail.com>"]
repository = "https://gitlab.redox-os.org/redox-os/pkgar"
edition.workspace = true

[dependencies]
pkgar-keys = { path = "../pkgar-keys", version = "0.2.4" }
pkgar-core = { path = "../pkgar-core", version = "0.2.4" }
ureq = { version = "3.4", default-features = false, features = ["rustls"] }
thiserror = "2"
